name: Test push tag

on:
  push:
    branches: 
      - main

permissions:
  contents: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # To attach provenance to the published package
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 
      - run: git tag latest
      # publish this new version to github (to give the Go module a new version)
      - run: git remote set-url origin https://github-actions[bot]:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      - run: git push origin latest
